
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


import ByteBuf from './bytebuf'

// loom 全局依赖
type loom = {
    i18n: { gettext: (key: string) => string },
    address: { data: Record<string, string> },
};

function gettext(key: string) {
    try {
        const i18n = ((window as any)['loom'] as loom | undefined)?.i18n;
        if (i18n && i18n.gettext) {
            return i18n.gettext(key) ?? key;
        }
        return key;
    } catch (error) {
        console.error(error);
        return key;
    }
}

function getAddress(key: string) {
    try {
        const address = ((window as any)['loom'] as loom)?.address;
        if (address && address.data) {
            return address.data[key] ?? key;
        }
        return key;
    } catch (error) {
        console.error(error);
        return key;
    }
}

 
export enum id_attr {
    hp = 1,
    atk = 2,
    def = 3,
}

 
 
export enum id_item {
    gem = 1,
    gold = 2,
    power = 3,
}

 
 
export enum id_res {
    item = 1,
    chest = 2,
    door = 3,
    chair = 4,
    house = 5,
}

 
 
export enum price_type {
    gem = 1,
    gold = 2,
    ad = -1,
    share = -2,
}

 





export class Consts {

    constructor(_buf_: ByteBuf) {
        { let n = Math.min(_buf_.readSize(), _buf_.size); this.initItems = []; for(let i = 0 ; i < n ; i++) { let _e0 ;_e0 = _buf_.readInt(); this.initItems.push(_e0);}}
    }

    /**
     * 初始金币数量
     */
    readonly initItems: number[]



    resolve(tables:Tables) {
        
    }
}





export class DialogOption {

    constructor(_buf_: ByteBuf) {
        this._title = _buf_.readString()
        this._icon = _buf_.readString()
        this.action = _buf_.readString()
    }

    public get title ():string { return gettext(this._title);}
    private readonly _title: string


    public get icon ():string { return getAddress(this._icon);}
    private readonly _icon: string


    readonly action: string



    resolve(tables:Tables) {
        
        
        
    }
}





export class float2 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.readFloat()
        this.y = _buf_.readFloat()
    }

    readonly x: number


    readonly y: number



    resolve(tables:Tables) {
        
        
    }
}





export class float3 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.readFloat()
        this.y = _buf_.readFloat()
        this.z = _buf_.readFloat()
    }

    readonly x: number


    readonly y: number


    readonly z: number



    resolve(tables:Tables) {
        
        
        
    }
}





export class float4 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.readFloat()
        this.y = _buf_.readFloat()
        this.z = _buf_.readFloat()
        this.w = _buf_.readFloat()
    }

    readonly x: number


    readonly y: number


    readonly z: number


    readonly w: number



    resolve(tables:Tables) {
        
        
        
        
    }
}





export class int2 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.readInt()
        this.y = _buf_.readInt()
    }

    readonly x: number


    readonly y: number



    resolve(tables:Tables) {
        
        
    }
}





export class int3 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.readInt()
        this.y = _buf_.readInt()
        this.z = _buf_.readInt()
    }

    readonly x: number


    readonly y: number


    readonly z: number



    resolve(tables:Tables) {
        
        
        
    }
}





export class int4 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.readInt()
        this.y = _buf_.readInt()
        this.z = _buf_.readInt()
        this.w = _buf_.readInt()
    }

    readonly x: number


    readonly y: number


    readonly z: number


    readonly w: number



    resolve(tables:Tables) {
        
        
        
        
    }
}





export class item {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.readInt()
        this._name = _buf_.readString()
        this._desc = _buf_.readString()
        this._ico = _buf_.readString()
    }

    /**
     * 道具id
     */
    readonly id: number


    /**
     * 道具名称
     */
    public get name ():string { return gettext(this._name);}
    private readonly _name: string


    /**
     * 道具描述
     */
    public get desc ():string { return gettext(this._desc);}
    private readonly _desc: string


    public get ico ():string { return getAddress(this._ico);}
    private readonly _ico: string



    resolve(tables:Tables) {
        
        
        
        
    }
}






export class TbConsts {

    private _data: Consts
    constructor(_buf_: ByteBuf) {
        if (_buf_.readInt() != 1) throw new Error('table mode=one, but size != 1')
        this._data = new Consts(_buf_)
    }

    getData(): Consts { return this._data; }
    /**
     * 初始金币数量
     */
    get  initItems(): number[] { return this._data.initItems; }

    resolve(tables:Tables) {
        this._data.resolve(tables)
    }
    
}




export class Tbitem {
    private _dataMap: Map<number, item>
    private _dataList: item[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, item>()
        this._dataList = []
        for(let n = _buf_.readInt(); n > 0; n--) {
            let _v: item
            _v = new item(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    get dic(): Map<number, item> { return this._dataMap; }
    get arr(): item[] { return this._dataList; }

    get(key: number): item | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}



export class Tables {
    private _TbConsts: TbConsts
    get tbConsts(): TbConsts  { return this._TbConsts;}
    private _Tbitem: Tbitem
    get tbitem(): Tbitem  { return this._Tbitem;}

    async load(tableNames?:string[]) {
        const binder = Tables.bind(this);
        for(let k in binder) {
            if (tableNames && tableNames.indexOf(k) === -1) continue;
            const address = `resources/tables/${k}.bin`;
            const resource = await Laya.loader.load(address, Laya.Loader.BUFFER) as Laya.TextResource;
            try {
                binder[k](new ByteBuf(new Uint8Array(resource.data)));
            } finally {
                Laya.loader.clearRes(address);
            }
        }
    }

    static bind(tb:Tables):Record<string, (data: ByteBuf)=>void> {
        return {
            "tbconsts":(data: ByteBuf)=> (tb._TbConsts = new TbConsts(data)).resolve(tb),
            "tbitem":(data: ByteBuf)=> (tb._Tbitem = new Tbitem(data)).resolve(tb)
        };
    }
}

declare global {
    interface LoomGlobal {
        tables: Tables;
    }
    var loom: LoomGlobal;
}

window.loom ??= {} as LoomGlobal;
window.loom.tables = new Tables();

